### ISSUE TITLE
patch Realtek Ltd RTS522A PCI Express Card Reader   Muhammad Awais

### ISSUE THREAD

**Issue by thegr8awais** [FIRSTPLATO/cardreader-kext#5]
Device 
Realtek Semiconductor Co., Ltd RTS522A PCI Express Card Reader   

 P05@1C,4/PXSX@0 
 
 
 pci10ec,522a   
 
 PciRoot(0x0)/Pci(0x1C,0x4)/Pci(0x0,0x0) 
 
 Can you please make patch for that?

**Comment by ipang-dwi** [comment]
Maybe, but please make sure, you follow this : Create new issue on https://github.com/FIRSTPLATO/cardreader-kext/issues, with title format #Request-Patch-your_name, and don't forget to give attachment Vendor and Device ID from DPCIManager or Hackintool.

**Comment by ipang-dwi** [comment]
I need attachment Vendor and Device ID from DPCIManager or Hackintool, to do patch.

**Comment by thegr8awais** [comment]
Vendor is: 0x10EC
Device is: 0x522A
[ALL PCIe devices list pastebin](https://pastebin.com/raw/wir7M9H8)

Let me know if need to provide something else, thanks

**Comment by ipang-dwi** [comment]
Sorry to make you waiting for it.. This is patch for your Card Reader
https://github.com/FIRSTPLATO/cardreader-kext/releases/tag/fp.18.02.2021
I wish it can be run flawlesly.. Give me your feedback after you trying it..

**Comment by thegr8awais** [comment]
It did not work
[https://pasteboard.co/JOP1t0G.jpg](https://pasteboard.co/JOP1t0G.jpg)

I asked someone in hackintosh channel on discord they are saying it's not compatible

**Comment by ipang-dwi** [comment]
which mac osx version you are use?? didn't you read your error and warning message on that's your verbose mode picture.. actually, your osx version can't recognized.. how do you patch it, using third party tool like hackintool, or you place it in your bootloader.. if you use osx mojave and later, you must disable SIP before.. fyi, I use realtek too, and it working well.. and all of my friend that us this method reported that they working well too.. sometimes, you must check your card reader, is pcie or usb type card reader..

**Comment by thegr8awais** [comment]
I am using BIG Sur 11.2.1 and opencore, So I placed those two kext files in opencore kext directory and then done os snapshot using propertree. then reported and it displayed that error.
I am sorry if i have not followed any steps correctly. 
[PCIe Devices Information](https://pasteboard.co/JOSfEvn.png)

Card is PCIe.
