### ISSUE TITLE
Request Patch USB SD Card Reader Samrth

### ISSUE THREAD

**Issue by samrth012** [FIRSTPLATO/cardreader-kext#6]
My card reader is from Realtek and is a USB one which is detected in USB but not as a card reader and hence it does not mount the SD Card 

Product id - 0x0129
Vendor id - 0x0bda
Location id - 0x14600000 / 5

Pls help me with the AppleStorageDevice.kext fix

**Comment by samrth012** [comment]
?

**Comment by gnpaone** [comment]
> My card reader is from Realtek and is a USB one which is detected in USB but not as a card reader and hence it does not mount the SD Card
> 
> Product id - 0x0129
> Vendor id - 0x0bda
> Location id - 0x14600000 / 5
> 
> Pls help me with the AppleStorageDevice.kext fix

Did it work for you?

**Comment by samrth012** [comment]
> > My card reader is from Realtek and is a USB one which is detected in USB but not as a card reader and hence it does not mount the SD Card
> > Product id - 0x0129
> > Vendor id - 0x0bda
> > Location id - 0x14600000 / 5
> > Pls help me with the AppleStorageDevice.kext fix
> 
> Did it work for you?

No the default one didn't.

**Comment by gnpaone** [comment]
> > > My card reader is from Realtek and is a USB one which is detected in USB but not as a card reader and hence it does not mount the SD Card
> > > Product id - 0x0129
> > > Vendor id - 0x0bda
> > > Location id - 0x14600000 / 5
> > > Pls help me with the AppleStorageDevice.kext fix
> > 
> > 
> > Did it work for you?
> 
> No the default one you have provided didn't.

Ohh ok. Please let me know if it works

**Comment by samrth012** [comment]
> > > > My card reader is from Realtek and is a USB one which is detected in USB but not as a card reader and hence it does not mount the SD Card
> > > > Product id - 0x0129
> > > > Vendor id - 0x0bda
> > > > Location id - 0x14600000 / 5
> > > > Pls help me with the AppleStorageDevice.kext fix
> > > 
> > > 
> > > Did it work for you?
> > 
> > 
> > No the default one you have provided didn't.
> 
> Ohh ok. Please let me know if it works

I need help regarding that only to make it work.

**Comment by samrth012** [comment]
If you could help

**Comment by gnpaone** [comment]
> If you could help

Actually, I don't know if posting link to some other discussion here is good but just follow [this](https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/page/4/) 
Just looking all the ways to make it work ☺️
